app:
  name: Transport Conveyor
  version: 1.0.0
  locale: Locale.US

  "researchTau": 5.0
  "deltaTau": 0.01
  "deltaLength" : 0.01
  initTransportSystemFiles:
    "E:\\A\\TransportSystem\\src\\main\\resources\\project\\data.json" :
      "id": "1"
      "startTimes": [0.0, 1.0]

prepareDataTableFormat:
  minWidth: 10
  cellFormat: "%8.5f"
