app:
  name: MyApp
  version: 1.0.0
  locale: Locale.US
  initTransportSystemFile: "E:\\A\\TransportSystem\\src\\main\\resources\\data.json"

prepareDataTableFormat:
  minWidth: 10
  cellFormat: "%8.5f"
